"""
Game configuration and constants for SpaceWar
"""

# Arena constants
ARENA_WIDTH = 800
ARENA_HEIGHT = 600

# Sun/Central body constants
SUN_X = ARENA_WIDTH / 2
SUN_Y = ARENA_HEIGHT / 2
SUN_RADIUS = 20
SUN_MASS = 1000
GRAVITY_CONSTANT = 35000

# Physics constants
FPS = 60
TICK_TIME = 1 / FPS
THRUST_ACCELERATION = 700
ROTATION_SPEED = 8
MAX_VELOCITY = 350
MIN_DISTANCE = 30
LINEAR_DAMPING = 0.94

# Projectile constants
MUZZLE_VELOCITY = 300
PROJECTILE_LIFESPAN = 300
PROJECTILE_RADIUS = 4
FIRE_COOLDOWN = 10

# Terrain constants
NUM_ASTEROIDS = 6
ASTEROID_MIN_RADIUS = 15
ASTEROID_MAX_RADIUS = 35

# Comet constants
COMET_DAMAGE_RADIUS = 60
COMET_DAMAGE_PER_TICK = 20
COMET_MASS = 500

# Player constants
STARTING_LIVES = 3
STARTING_HEALTH = 100
INVULNERABILITY_TIME = 180

# Ultimate ability constants
ULTIMATE_CHARGE_RATE = 0.5  # % per frame
ULTIMATE_THRESHOLD = 100
EMP_PROJECTILE_COUNT = 16
EMP_PROJECTILE_SPEED = 250

# Ultimate types
ULTIMATE_EMP_BURST = "EMP_BURST"
ULTIMATE_DEATH_RAY = "DEATH_RAY"
ULTIMATE_GOD_MODE = "GOD_MODE"

# Skill pack spawning
SKILL_PACK_SPAWN_INTERVAL_MIN = 480  # 8 seconds at 60 FPS
SKILL_PACK_SPAWN_INTERVAL_MAX = 720  # 12 seconds
SKILL_PACK_DRIFT_SPEED = 30  # Slow drift speed
SKILL_PACK_RADIUS = 15
DEATH_RAY_DURATION = 90  # 1.5 seconds at 60 FPS
DEATH_RAY_WIDTH = 30  # Laser width for collision
DEATH_RAY_MAX_RANGE = 2000  # Laser range
DEATH_RAY_DAMAGE_PER_FRAME = 50

# Power-ups
POWERUP_SPAWN_INTERVAL = 600  # 10 seconds at 60 FPS
POWERUP_LIFETIME = 600  # 10 seconds before despawn
SHIELD_DURATION = 600  # 10 seconds of shield

# Electromagnetic Zone
EM_ZONE_X = 200
EM_ZONE_Y = 150
EM_ZONE_RADIUS = 80
EM_FORCE_MAGNITUDE = 400
